"""
Training driver for model_known_node.KnownNodeFilter -- the known-F/Q/h/R
TDOA filter with a Daum-Huang-plus-learned-residual measurement update (see
model_known_node.py's module docstring for the full rationale).

Unlike train.py, there is no known_dynamics/known_measurement choice
here -- F, Q, h(x), and R are always known/exact, ported directly from
tdoa_data_gen.py / baseline_edh_tdoa.py. Currently TDOA-only (that's what
KnownTDOAMeasurement implements).
"""
import argparse
import os

import torch
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint, EarlyStopping

from dataset import FileTrackingDataModule
from model_known_node import KnownNodeFilter
import tdoa_data_gen as tdg


def build_logger(args, run_name: str, hparams: dict):
    if args.logger == 'wandb':
        from pytorch_lightning.loggers import WandbLogger
        return WandbLogger(project=args.wandb_project, entity=args.wandb_entity,
                            name=run_name, config=hparams)
    from pytorch_lightning.loggers import TensorBoardLogger
    return TensorBoardLogger(save_dir=args.save_dir, name=run_name)


def main():
    parser = argparse.ArgumentParser(
        description="Train model_known_node.KnownNodeFilter "
                    "(known F/Q/h/R, learned Daum-Huang residual only).")

    # ── Data ──────────────────────────────────────────────────────────────────
    parser.add_argument('--data_path', type=str, required=True,
                        help='Path to a .pt file generated by tdoa_data_gen.py.')
    parser.add_argument('--dataset_type', type=str, default='tdoa',
                        choices=['tdoa'],
                        help='Only tdoa is supported -- KnownTDOAMeasurement is '
                             'TDOA-specific (range-difference h(x)).')
    parser.add_argument('--seq_len',    type=int, default=100)
    parser.add_argument('--stride',     type=int, default=1)
    parser.add_argument('--batch_size', type=int, default=64)

    # ── Core dims ─────────────────────────────────────────────────────────────
    parser.add_argument('--hidden_dim', type=int, default=64,
                        help='Width of the learned Daum-Huang residual MLP.')
    parser.add_argument('--num_particles', type=int, default=50,
                        help='Must be > 1 -- P is estimated empirically from '
                             'particle spread, matching baseline_edh_tdoa.py.')
    parser.add_argument('--matrix_free', action='store_true',
                        help='Drop the closed-form Daum-Huang term (A(lam)x+b(lam)) '
                             'from the measurement flow entirely -- the ODEfunc '
                             'becomes structurally identical to model.py\'s '
                             'PFFODEFunc (net + innov_skip only, no H/P_inv/R_inv '
                             'anywhere in the vector field). Known F/Q still drive '
                             'the predict step and exact h(x) still drives the '
                             'innovation -- only the measurement-UPDATE vector '
                             'field becomes matrix-blind. Also skips the Jacobian '
                             'and empirical-covariance matrix inverse at train/eval '
                             'time (real compute savings, not just unused args). '
                             'Use this to isolate whether the analytical term '
                             'itself helps, vs. just having known F/Q/h(x).')
    parser.add_argument('--cov_conditioning', action='store_true',
                        help='Only valid with --matrix_free. Conditions the '
                             'measurement flow on cov_signal, the upper '
                             'triangle of an analytically-propagated Kalman '
                             'covariance (P_prior = F @ P_post_prev @ F.T + Q, '
                             'P_post via a Kalman gain update using the known '
                             'H/R) -- the matrix-free analogue of '
                             'model.py\'s uncertainty_rnn conditioning, '
                             'except computed in closed form rather than '
                             'learned, and decoupled from num_particles (so it '
                             'stays meaningful even though num_particles=50 is '
                             'what\'s actually used here, unlike the empirical '
                             'particle-spread covariance it replaces, which '
                             'degenerates to a constant at num_particles=1).')

    # ── Loss ──────────────────────────────────────────────────────────────────
    parser.add_argument('--loss_type', type=str, default='huber',
                        choices=['l1', 'l2', 'mse', 'huber'],
                        help='No gaussian_nll here -- this model has no learned '
                             'uncertainty head (EDH has none either, so there is '
                             'nothing to compare a calibrated uncertainty against).')
    parser.add_argument('--huber_delta', type=float, default=1.0)

    # ── Integration ───────────────────────────────────────────────────────────
    parser.add_argument('--integration_steps', type=int, default=4,
                        help='RK4 stages (4) x integration_steps solver calls per '
                             'timestep -- restricted to 4 (matching '
                             'model.py/train.py\'s own default) rather '
                             'than baseline_edh_tdoa.py\'s exact_daum_huang_step '
                             'default of 10, since each call recomputes a batched '
                             'matrix inverse (see the compute-cost discussion in '
                             'session). Any EDH comparison this checkpoint is '
                             'evaluated against should be run with a matching '
                             'num_steps -- see no_control_eval.py\'s '
                             '--edh_num_steps, which now auto-matches the model\'s '
                             'own integration_steps by default.')
    parser.add_argument('--integration_type', type=str, default='rk4',
                        choices=['rk4', 'euler'],
                        help='euler + --lam_schedule uniform reproduces EDH\'s own '
                             'fixed-step Euler integration exactly (verified '
                             'directly against baseline_edh_tdoa.py\'s '
                             'exact_daum_huang_step at delta_theta=0, see session '
                             'history); rk4 is a genuinely different, more accurate '
                             'integration of the same vector field.')
    parser.add_argument('--lam_schedule', type=str, default='exponential',
                        choices=['exponential', 'uniform'])

    # ── Process noise (matches tdoa_data_gen.py's true generative process) ────
    parser.add_argument('--q_pos', type=float, default=1e-4,
                        help='Position process-noise variance -- must match '
                             'tdoa_data_gen.py\'s actual value to be a correct '
                             '"known" Q, not an approximation.')
    parser.add_argument('--q_vel', type=float, default=1e-5,
                        help='Velocity process-noise variance -- see --q_pos.')

    # ── Training ──────────────────────────────────────────────────────────────
    parser.add_argument('--lr', type=float, default=1e-3)
    parser.add_argument('--num_epochs', type=int, default=100,
                        help='Absolute target epoch, not "epochs to add" -- see '
                             'train.py\'s --num_epochs docs for the '
                             '--resume_from_ckpt interaction.')
    parser.add_argument('--early_stop_patience', type=int, default=15)
    parser.add_argument('--resume_from_ckpt', type=str, default=None)

    # ── Logging ───────────────────────────────────────────────────────────────
    parser.add_argument('--logger', type=str, default='tensorboard',
                        choices=['wandb', 'tensorboard'])
    parser.add_argument('--save_dir', type=str, default='known_node_runs')
    parser.add_argument('--wandb_project', type=str, default='NODiF-known-node')
    parser.add_argument('--wandb_entity', type=str, default=None)

    args = parser.parse_args()

    print("=" * 58)
    print("  model_known_node training driver")
    print("=" * 58)
    for k, v in vars(args).items():
        print(f"  {k:<26} = {v}")
    print("=" * 58)

    # ── Data ──────────────────────────────────────────────────────────────────
    # normalize=False: KnownNodeFilter wants raw physical-unit trajectories
    # directly (F/Q/h/R are all physical) -- it does its own normalize/
    # denormalize round-trip internally, only around the correction-step
    # integration (see model_known_node.py's forward()).
    dm = FileTrackingDataModule(
        data_path    = args.data_path,
        seq_len      = args.seq_len,
        stride       = args.stride,
        batch_size   = args.batch_size,
        dataset_type = args.dataset_type,
        normalize    = False,
    )
    dm.setup()

    # ── Model ─────────────────────────────────────────────────────────────────
    model = KnownNodeFilter(
        state_dim         = dm.state_dim,
        obs_dim           = dm.obs_dim,
        hidden_dim        = args.hidden_dim,
        num_particles     = args.num_particles,
        lr                = args.lr,
        integration_steps = args.integration_steps,
        integration_type  = args.integration_type,
        lam_schedule      = args.lam_schedule,
        loss_type         = args.loss_type,
        huber_delta       = args.huber_delta,
        matrix_free       = args.matrix_free,
        cov_conditioning  = args.cov_conditioning,
    )

    # ── Register known F/Q (physical units, matching tdoa_data_gen.py exactly --
    # NOT main.py's build_ssm_matrices, which uses a continuous-white-noise-
    # acceleration Q that doesn't match tdoa_data_gen.py's actual diagonal Q;
    # see baseline_edh_tdoa.py's docstring for the same distinction) ──────────
    dt = tdg.DT
    F = torch.tensor([
        [1.0, 0.0, dt,  0.0],
        [0.0, 1.0, 0.0, dt ],
        [0.0, 0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0, 1.0],
    ], dtype=torch.float32)
    Q = torch.diag(torch.tensor(
        [args.q_pos, args.q_pos, args.q_vel, args.q_vel], dtype=torch.float32))
    Q_chol = torch.linalg.cholesky(Q)
    model.set_ssm(F, Q_chol)

    # ── Register known measurement (physical units) ─────────────────────────
    model.set_measurement(
        L_REF  = torch.tensor(tdg.L_REF),
        L_RX   = torch.tensor(tdg.L_RX),
        L_REF2 = torch.tensor(tdg.L_REF2),
        L_RX2  = torch.tensor(tdg.L_RX2),
        measurement_std = tdg.MEASUREMENT_STD,
    )

    # ── Register dataset normalisation stats (denormalises at _unroll's entry;
    # every downstream computation is physical -- see module docstring) ──────
    model.set_norm_stats(dm.t_mean, dm.t_std, dm.m_mean, dm.m_std)

    # Enables on_validation_epoch_end's full-trajectory rollout RMSE logging.
    model.val_dataset = dm.val_dataset

    # ── Callbacks ─────────────────────────────────────────────────────────────
    mf_tag = "_matrixfree" if args.matrix_free else ""
    cov_tag = "_covcond" if args.cov_conditioning else ""
    run_name = f"known_node_{args.loss_type}_{args.integration_type}_{args.lam_schedule}{mf_tag}{cov_tag}"
    ckpt_dir = os.path.join(args.save_dir, run_name, 'checkpoints')

    checkpoint_cb = ModelCheckpoint(
        monitor    = 'val_loss',
        mode       = 'min',
        save_top_k = 5,
        filename   = 'best_{val_loss:.4f}',
        dirpath    = ckpt_dir,
    )
    early_stop_cb = EarlyStopping(
        monitor  = 'val_loss',
        patience = args.early_stop_patience,
        mode     = 'min',
    )

    logger = build_logger(args, run_name, vars(args))

    # ── Trainer ───────────────────────────────────────────────────────────────
    trainer = pl.Trainer(
        max_epochs        = args.num_epochs,
        callbacks         = [checkpoint_cb, early_stop_cb],
        logger            = logger,
        gradient_clip_val = 5.0,
        accelerator       = 'auto',
        devices           = 1,
    )
    if args.resume_from_ckpt is not None:
        print(f"  Resuming from: {args.resume_from_ckpt} (target epoch: {args.num_epochs})")
    trainer.fit(model, datamodule=dm, ckpt_path=args.resume_from_ckpt)

    # ── Save final checkpoint ─────────────────────────────────────────────────
    os.makedirs(ckpt_dir, exist_ok=True)
    final_path = os.path.join(ckpt_dir, 'final_model.ckpt')
    trainer.save_checkpoint(final_path)
    print(f"\nFinished training.")
    print(f"  Best  -> {checkpoint_cb.best_model_path}")
    print(f"  Final -> {final_path}")


if __name__ == '__main__':
    main()
