"""
Training driver for model.ModularNeuralODEFilter.

main.py (the current repo's driver) can't be reused unmodified here — its
GMM branch passes constructor kwargs (num_modes, repulsion_strength,
repulsion_bandwidth, adjoint, adaptive_steps, init_noise_std) that
model's __init__ doesn't accept, and it imports model_experimental
directly. This script wires up only the kwargs model actually
supports, defaulting to this checkpoint family's documented config:
  loss_type=gaussian_nll, ssm_style_predict=true, per_particle_context=true,
  uncertainty_gru_dim=16, state_gru_dim=32, num_particles=1

Data: this folder ships the acoustic data-generation scripts (data_gen.py +
config.py), not generated data. Run data_gen.py first (see its __main__
block / NPFFConfig in config.py) to produce a .pt file, then point
--data_path at it.
"""
import argparse
import os

import torch
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint, EarlyStopping

from dataset import FileTrackingDataModule
from model import ModularNeuralODEFilter


def build_logger(args, run_name: str, hparams: dict):
    if args.logger == 'wandb':
        from pytorch_lightning.loggers import WandbLogger
        return WandbLogger(project=args.wandb_project, entity=args.wandb_entity,
                            name=run_name, config=hparams)
    from pytorch_lightning.loggers import TensorBoardLogger
    return TensorBoardLogger(save_dir=args.save_dir, name=run_name)


def main():
    parser = argparse.ArgumentParser(
        description="Train model.ModularNeuralODEFilter "
                    "(ssm_style_run_gaussian_nll_mlp_varhead config).")

    # ── Data ──────────────────────────────────────────────────────────────────
    parser.add_argument('--data_path',    type=str, required=True,
                        help='Path to a .pt file generated by data_gen.py / lorenz.py / '
                             'ackermann_dataset.py.')
    parser.add_argument('--dataset_type', type=str, default='acoustic')
    parser.add_argument('--seq_len',      type=int, default=100)
    parser.add_argument('--stride',       type=int, default=1)
    parser.add_argument('--batch_size',   type=int, default=64)
    parser.add_argument('--use_control',  action='store_true',
                        help='Controlled mode (e.g. ackermann_dataset.py output). '
                             'Batch becomes (obs, states, controls, mask); routes through '
                             'FileTrackingDataModule._setup_controlled(), which applies NO '
                             'normalisation (states/obs/controls are used at their raw, '
                             'physical scale) -- unlike the uncontrolled path.')
    parser.add_argument('--control_dim',  type=int, default=2,
                        help='Only used when --use_control (ackermann_dataset.py: 2).')

    parser.add_argument('--training_phase', type=int, default=2, choices=[1, 2])

    # ── Core dims ─────────────────────────────────────────────────────────────
    parser.add_argument('--hidden_dim',    type=int, default=64)
    parser.add_argument('--state_gru_dim', type=int, default=32,
                        help='Checkpoint default is 32, not the current repo\'s 16.')
    parser.add_argument('--sensor_obs_dim', type=int, default=None)

    # ── Documented checkpoint architecture (defaults match it exactly) ────────
    parser.add_argument('--per_particle_context', action='store_true', default=True)
    parser.add_argument('--no_per_particle_context', dest='per_particle_context',
                        action='store_false')
    parser.add_argument('--gru_num_layers', type=int, default=1)
    parser.add_argument('--state_rnn_per_gate_orthogonal', action='store_true',
                        help='Split state_rnn\'s weight_hh into its 3 stacked GRU gate '
                             'blocks (reset/update/candidate) and orthogonally initialise '
                             'each independently, instead of the default whole-matrix '
                             'orthogonal_ (which only makes the 3 blocks\' columns '
                             'orthonormal as a stack, not each gate\'s own hidden-to-hidden '
                             'transform). Targets _gru_init\'s single cold pass over x_0 -- '
                             'every other state_rnn call already has a real hidden state '
                             'carried forward from _gru_step. Only affects state_rnn, not '
                             'uncertainty_rnn.')
    parser.add_argument('--ssm_style_predict', action='store_true', default=True)
    parser.add_argument('--no_ssm_style_predict', dest='ssm_style_predict',
                        action='store_false')
    parser.add_argument('--ssm_residual_predict', action='store_true')
    parser.add_argument('--ssm_predictor_layernorm', action='store_true',
                        help='LayerNorm on physics_predictor\'s delta-network input (x_t, or '
                             'h_t under --ssm_wide_context_input) before its first layer -- '
                             'not on x_t when used as the residual anchor, which stays in '
                             'physical-state scale. Targets a measured problem: that input\'s '
                             'distribution at t=1 (from a once-per-trajectory cold _gru_init '
                             'pass) differs measurably from its distribution at t>=2 (from '
                             '~N_steps of real _gru_step updates) -- up to a 2.9 std-dev shift '
                             'in the worst dimension on a trained checkpoint. Makes delta '
                             'robust to that shift directly (Ba, Kiros & Hinton, "Layer '
                             'Normalization", 2016) instead of trying to eliminate the shift '
                             'itself, which every prior attempt (raw x_0 substitution, an '
                             'auxiliary reconstruction loss) only partially fixed or broke. No '
                             'effect when --ssm_style_predict is off.')
    parser.add_argument('--ssm_predictor_layers', type=int, default=1)
    parser.add_argument('--ssm_wide_context_input', action='store_true')
    parser.add_argument('--ssm_continuous_innovation', action='store_true')
    parser.add_argument('--uncertainty_conditioning', action='store_true', default=True,
                        help='Feed both var_head\'s (posterior/innovation) and '
                             'prior_var_head\'s (prior/propagation) uncertainty estimates '
                             'as extra conditioning input to measurement_flow only (never '
                             'physics_predictor) -- in spirit (not literal Kalman-gain math) '
                             'mimicking Q and R both acting at the correction step. NOT '
                             'detached (see model.py\'s docstring for the '
                             'previously-observed collapse risk this reopens -- deliberate '
                             'for now). Requires --loss_type gaussian_nll and '
                             '--ssm_style_predict (both the default).')
    parser.add_argument('--learned_init_encoder', action='store_true',
                        help='Seed state_rnn\'s h0 at t=0 from a small learned '
                             'Linear(state_dim, state_gru_dim) applied to the true initial '
                             'state, instead of noise (train) / zero (eval). Standard '
                             'encoder-conditioned initial-hidden-state pattern from seq2seq '
                             '(Sutskever et al. 2014, Cho et al. 2014) -- targets the '
                             'cold-start t=1 prediction error (measured ~2.4km on a real '
                             'trajectory) at its source rather than working around it.')
    parser.add_argument('--init_recon_weight', type=float, default=0.0,
                        help='Weight on an auxiliary loss, '
                             '||context_readout(init_encoder(x_0)) - x_0||^2, added directly '
                             'to the training objective. No effect when '
                             '--learned_init_encoder is off. init_encoder only reaches the '
                             'main loss through a long, diluted path (once per trajectory, '
                             'vs. state_rnn\'s ~N_steps firings) -- a prior attempt at boosting '
                             'its LR ~15x changed grad_norm/init_encoder.* a lot (~1:230 -> '
                             '~1:15 relative to dominant layers) but left the actual '
                             'reconstruction error and eval-time cold-start spike unchanged, '
                             'showing the problem is the gradient\'s target, not its magnitude. '
                             'This term gives init_encoder a short, direct path instead (same '
                             'idea as GoogLeNet\'s auxiliary classifier heads -- Szegedy et al. '
                             '2015; formalized as "deeply-supervised nets" by Lee et al. 2015). '
                             'Try 1.0 as a starting point.')
    parser.add_argument('--direct_init_predict', action='store_true',
                        help='physics_predictor\'s first call (t=1) uses the raw, exact x_0 '
                             'directly instead of context_readout(state_context) -- '
                             'context_readout/state_context are only ever asked to '
                             'reconstruct a state starting at t=2 (the corrected posterior '
                             'from t=1, via the ordinary _gru_step), the same thing it '
                             'already does at every t>=2. Removes the once-per-trajectory '
                             '_gru_init round-trip from physics_predictor\'s critical path '
                             'entirely, rather than trying to make it reconstruct x_0 '
                             'accurately (--learned_init_encoder / --init_recon_weight). '
                             'Requires --ssm_style_predict, no --ssm_wide_context_input. Can '
                             'be combined with --learned_init_encoder / --init_recon_weight '
                             '(they no longer matter for t=1\'s prediction accuracy once this '
                             'is on, but don\'t conflict).')
    parser.add_argument('--meas_model_layers', type=int, default=1)
    parser.add_argument('--meas_model_layernorm', action='store_true')

    # ── Loss / uncertainty ─────────────────────────────────────────────────────
    parser.add_argument('--loss_type', type=str, default='gaussian_nll',
                        choices=['l1', 'l2', 'mse', 'huber', 'gaussian_nll'])
    parser.add_argument('--huber_delta', type=float, default=1.0)
    parser.add_argument('--min_variance', type=float, default=1e-2)
    parser.add_argument('--prior_nll_weight', type=float, default=1.0,
                        help='Weight on the prior-belief NLL term: total loss = '
                             'nll_post + prior_nll_weight * nll_prior. No principled '
                             'derived value -- 1.0 (unweighted sum) is a starting '
                             'point; see model.py\'s __init__ docstring.')
    parser.add_argument('--uncertainty_gru_dim', type=int, default=16)
    parser.add_argument('--uncertainty_rnn_lstm', action='store_true',
                        help='Use an nn.LSTMCell for uncertainty_rnn instead of the default '
                             'nn.GRUCell -- gives it a separate cell state with its own '
                             'additive, forget-gated update path (forget-gate bias '
                             'initialised to 1, Jozefowicz, Zaremba & Sutskever, ICML 2015). '
                             'Externally uncertainty_h stays a single tensor at every call '
                             'site; only var_head_in_dim-relevant behaviour (its dimension, '
                             'uncertainty_conditioning\'s _uncertainty_dim) is unaffected -- '
                             'the packed [h ‖ c] state is internal to _uncertainty_rnn_step.')
    parser.add_argument('--num_particles', type=int, default=1,
                        help='With gaussian_nll, num_particles>1 scores a K-component '
                             'Gaussian mixture (log-sum-exp over particles) instead of a '
                             'single Gaussian -- each particle is one mixture component with '
                             'its own predicted mean, variance, and weight. Exactly reduces '
                             'to the original single-Gaussian NLL at num_particles=1 (the '
                             'default). See model.py\'s _gaussian_nll_step.')

    # ── Integration ────────────────────────────────────────────────────────────
    parser.add_argument('--integration_steps', type=int, default=4)
    parser.add_argument('--integration_type', type=str, default='rk4',
                        choices=['rk4', 'euler', 'adaptive'])
    parser.add_argument('--adaptive_steps', action='store_true',
                        help='Use torchdiffeq\'s adaptive Dopri5 integrator '
                             'instead of the fixed-step rk4/euler stepper. '
                             'Also implied by --integration_type adaptive. '
                             'integration_steps/lam_schedule are unused when '
                             'this is set (torchdiffeq picks its own steps).')
    parser.add_argument('--adjoint', action='store_true',
                        help='Use torchdiffeq\'s adjoint sensitivity method '
                             '(odeint_adjoint) for backprop through the ODE '
                             'solve -- O(1) memory in solver steps at the '
                             'cost of a second backward-time solve for the '
                             'gradient. Only has an effect when '
                             '--adaptive_steps (or --integration_type '
                             'adaptive) is also set -- silently ignored by '
                             'the fixed-step rk4/euler path otherwise.')
    parser.add_argument('--inference_rtol', type=float, default=1e-4,
                        help='torchdiffeq error tolerance, only consulted '
                             'when --adaptive_steps is set.')
    parser.add_argument('--inference_atol', type=float, default=1e-5,
                        help='torchdiffeq error tolerance, only consulted '
                             'when --adaptive_steps is set.')
    parser.add_argument('--lam_schedule', type=str, default='exponential',
                        choices=['exponential', 'uniform'])

    # ── Particle diversity (num_particles>1 only) ──────────────────────────────
    parser.add_argument('--particle_init_diversity_std', type=float, default=0.0,
                        help='Perturbs ONLY the initial (t=0) particle cloud '
                             'when num_particles>1 -- NOT a process-noise/Q '
                             'substitute (no-op at num_particles=1 regardless '
                             'of value). See model.py\'s __init__ '
                             'docstring for the full rationale.')

    # ── Stiff-ODE / augmented-ODE (off by default, matching the checkpoint) ───
    parser.add_argument('--equation_scaling', action='store_true')
    parser.add_argument('--deep_gelu_ode', action='store_true')
    parser.add_argument('--ode_depth', type=int, default=6)
    parser.add_argument('--ode_width', type=int, default=5)
    parser.add_argument('--ode_residual', action='store_true')
    parser.add_argument('--aug_dim', type=int, default=0)

    # ── Training ───────────────────────────────────────────────────────────────
    parser.add_argument('--lr', type=float, default=1e-3)
    parser.add_argument('--gradient_clip_val', type=float, default=5.0,
                        help='Global-norm gradient clip, passed straight to '
                             'pl.Trainer(gradient_clip_val=...). Lower this if '
                             'grad_norm_global_preclip/grad_clip_ratio (see model.py\'s '
                             'on_after_backward) show severe, persistent spikes rather than a '
                             'brief early-training transient -- see session history.')
    parser.add_argument('--num_epochs', type=int, default=100,
                        help='Absolute target epoch, not "epochs to add" -- with '
                             '--resume_from_ckpt, this must be set higher than the '
                             'checkpoint\'s own epoch count (e.g. a checkpoint saved at '
                             'epoch 99 with --num_epochs 100 unchanged will train for 0 '
                             'further epochs and exit immediately).')
    parser.add_argument('--early_stop_patience', type=int, default=15)
    parser.add_argument('--resume_from_ckpt', type=str, default=None,
                        help='Path to a .ckpt file to resume training from -- restores '
                             'model weights, optimizer state, LR scheduler state, and '
                             'epoch count (full Trainer.fit(ckpt_path=...) resume, not '
                             'just weight loading). Remember to raise --num_epochs to the '
                             'new target total.')

    # ── Logging ────────────────────────────────────────────────────────────────
    parser.add_argument('--logger', type=str, default='tensorboard',
                        choices=['wandb', 'tensorboard'])
    parser.add_argument('--save_dir', type=str, default='legacy_runs')
    parser.add_argument('--wandb_project', type=str, default='NODiF-legacy')
    parser.add_argument('--wandb_entity', type=str, default=None)

    args = parser.parse_args()

    print("=" * 58)
    print("  model training driver")
    print("=" * 58)
    for k, v in vars(args).items():
        print(f"  {k:<26} = {v}")
    print("=" * 58)

    if args.use_control and args.equation_scaling:
        # dataset.py's _setup_controlled() has no use_minmax_norm handling at
        # all (only _setup_uncontrolled reads it) -- equation_scaling would
        # silently no-op rather than actually apply, so refuse rather than
        # let the flag look like it did something.
        raise NotImplementedError(
            "--equation_scaling has no effect in controlled (--use_control) mode -- "
            "FileTrackingDataModule._setup_controlled() doesn't apply any "
            "normalisation regardless of use_minmax_norm. Drop --equation_scaling.")

    # ── Data ──────────────────────────────────────────────────────────────────
    dm = FileTrackingDataModule(
        data_path       = args.data_path,
        seq_len         = args.seq_len,
        stride          = args.stride,
        batch_size      = args.batch_size,
        dataset_type    = args.dataset_type,
        use_control     = args.use_control,
        use_minmax_norm = args.equation_scaling,
    )
    dm.setup()

    # ── Model ─────────────────────────────────────────────────────────────────
    model = ModularNeuralODEFilter(
        state_dim              = dm.state_dim,
        obs_dim                = dm.obs_dim,
        use_control              = args.use_control,
        control_dim              = args.control_dim,
        hidden_dim              = args.hidden_dim,
        state_gru_dim           = args.state_gru_dim,
        per_particle_context    = args.per_particle_context,
        gru_num_layers          = args.gru_num_layers,
        state_rnn_per_gate_orthogonal = args.state_rnn_per_gate_orthogonal,
        ssm_style_predict       = args.ssm_style_predict,
        ssm_residual_predict    = args.ssm_residual_predict,
        ssm_predictor_layernorm = args.ssm_predictor_layernorm,
        ssm_predictor_layers    = args.ssm_predictor_layers,
        meas_model_layers       = args.meas_model_layers,
        meas_model_layernorm    = args.meas_model_layernorm,
        ssm_wide_context_input  = args.ssm_wide_context_input,
        ssm_continuous_innovation = args.ssm_continuous_innovation,
        uncertainty_conditioning = args.uncertainty_conditioning,
        learned_init_encoder    = args.learned_init_encoder,
        init_recon_weight       = args.init_recon_weight,
        direct_init_predict     = args.direct_init_predict,
        training_phase          = args.training_phase,
        num_particles           = args.num_particles,
        lr                      = args.lr,
        integration_steps       = args.integration_steps,
        loss_type               = args.loss_type,
        huber_delta              = args.huber_delta,
        min_variance             = args.min_variance,
        prior_nll_weight         = args.prior_nll_weight,
        uncertainty_gru_dim      = args.uncertainty_gru_dim,
        uncertainty_rnn_lstm     = args.uncertainty_rnn_lstm,
        integration_type         = args.integration_type,
        adaptive_steps            = args.adaptive_steps,
        adjoint                    = args.adjoint,
        inference_rtol             = args.inference_rtol,
        inference_atol             = args.inference_atol,
        lam_schedule              = args.lam_schedule,
        particle_init_diversity_std = args.particle_init_diversity_std,
        equation_scaling          = args.equation_scaling,
        deep_gelu_ode             = args.deep_gelu_ode,
        ode_depth                 = args.ode_depth,
        ode_width                 = args.ode_width,
        ode_residual               = args.ode_residual,
        aug_dim                    = args.aug_dim,
        sensor_obs_dim             = args.sensor_obs_dim,
    )

    if args.equation_scaling:
        model.set_equation_scaling(dm.correction_scale)
        print(f"  Equation scaling registered (correction_scale="
              f"{dm.correction_scale.tolist()}).")

    # Enables on_validation_epoch_end's full-trajectory rollout RMSE logging.
    # Controlled-mode datasets (dm._setup_controlled()) have no t_mean/t_std
    # attribute at all -- no normalisation is applied to that path, so use
    # the identity (mean=0, std=1) rather than reading an attribute that
    # doesn't exist there.
    model.val_dataset = dm.val_dataset
    if args.use_control:
        model.val_t_mean = torch.zeros(dm.state_dim)
        model.val_t_std  = torch.ones(dm.state_dim)
    else:
        model.val_t_mean = dm.t_mean.squeeze().cpu()
        model.val_t_std  = dm.t_std.squeeze().cpu()

    # ── Callbacks ─────────────────────────────────────────────────────────────
    run_name = f"legacy_{args.loss_type}_{args.integration_type}_{args.lam_schedule}"
    ckpt_dir = os.path.join(args.save_dir, run_name, 'checkpoints')

    checkpoint_cb = ModelCheckpoint(
        monitor    = 'val_loss',
        mode       = 'min',
        save_top_k = 5,
        filename   = 'best_{val_loss:.4f}',
        dirpath    = ckpt_dir,
    )
    early_stop_cb = EarlyStopping(
        monitor  = 'val_loss',
        patience = args.early_stop_patience,
        mode     = 'min',
    )

    logger = build_logger(args, run_name, vars(args))

    # ── Trainer ───────────────────────────────────────────────────────────────
    trainer = pl.Trainer(
        max_epochs        = args.num_epochs,
        callbacks         = [checkpoint_cb, early_stop_cb],
        logger            = logger,
        gradient_clip_val = args.gradient_clip_val,
        accelerator       = 'auto',
        devices           = 1,
    )
    if args.resume_from_ckpt is not None:
        print(f"  Resuming from: {args.resume_from_ckpt} (target epoch: {args.num_epochs})")
    trainer.fit(model, datamodule=dm, ckpt_path=args.resume_from_ckpt)

    # ── Save final checkpoint ─────────────────────────────────────────────────
    os.makedirs(ckpt_dir, exist_ok=True)
    final_path = os.path.join(ckpt_dir, 'final_model.ckpt')
    trainer.save_checkpoint(final_path)
    print(f"\nFinished training.")
    print(f"  Best  -> {checkpoint_cb.best_model_path}")
    print(f"  Final -> {final_path}")


if __name__ == '__main__':
    main()
